PROTOCOL_VERSION = "1.0"

MESSAGE_TYPE_SHOT_RESULT = "shot_result"
SUPPORTED_MESSAGE_TYPES = {MESSAGE_TYPE_SHOT_RESULT}

RESULT_HIT = "hit"
RESULT_MISS = "miss"
ALLOWED_RESULTS = {RESULT_HIT, RESULT_MISS}

LED_GREEN = "green"
LED_RED = "red"
ALLOWED_LED_COLORS = {LED_GREEN, LED_RED}

DEFAULT_LED_DURATION_MS = 500
MIN_LED_DURATION_MS = 1
MAX_LED_DURATION_MS = 60000

SOURCE_MODULE_GUI = "gui"

MIN_COORDINATE_VALUE = 0
MAX_COORDINATE_VALUE = 4095
